1: 
	rm ./bin/ejercicio01.bin; clear; clear; g++  -o ./bin/ejercicio01.bin ejercicio01.cpp; ./bin/ejercicio01.bin

2: 
	rm ./bin/ejercicio02.bin; clear; clear; g++  -o ./bin/ejercicio02.bin ejercicio02.cpp; ./bin/ejercicio02.bin

3: 
	rm ./bin/ejercicio03.bin; clear; clear; g++  -o ./bin/ejercicio03.bin ejercicio03.cpp; ./bin/ejercicio03.bin

4: 
	rm ./bin/ejercicio04.bin; clear; clear; g++  -o ./bin/ejercicio04.bin ejercicio04.cpp; ./bin/ejercicio04.bin

5: 
	rm ./bin/ejercicio05.bin; clear; clear; g++  -o ./bin/ejercicio05.bin ejercicio05.cpp; ./bin/ejercicio05.bin

6: 
	rm ./bin/ejercicio06.bin; clear; clear; g++  -o ./bin/ejercicio06.bin ejercicio06.cpp; ./bin/ejercicio06.bin

7: 
	rm ./bin/ejercicio07.bin; clear; clear; g++  -o ./bin/ejercicio07.bin ejercicio07.cpp; ./bin/ejercicio07.bin

8: 
	rm ./bin/ejercicio08.bin; clear; clear; g++  -o ./bin/ejercicio08.bin ejercicio08.cpp; ./bin/ejercicio08.bin

9: 
	rm ./bin/ejercicio09.bin; clear; clear; g++  -o ./bin/ejercicio09.bin ejercicio09.cpp; ./bin/ejercicio09.bin

10: 
	rm ./bin/ejercicio10.bin; clear; clear; g++  -o ./bin/ejercicio10.bin ejercicio10.cpp; ./bin/ejercicio10.bin

11: 
	rm ./bin/ejercicio11.bin; clear; clear; g++  -o ./bin/ejercicio11.bin ejercicio11.cpp; ./bin/ejercicio11.bin

12: 
	rm ./bin/ejercicio12.bin; clear; clear; g++  -o ./bin/ejercicio12.bin ejercicio12.cpp; ./bin/ejercicio12.bin

13: 
	rm ./bin/ejercicio13.bin; clear; clear; g++  -o ./bin/ejercicio13.bin ejercicio13.cpp; ./bin/ejercicio13.bin

14: 
	rm ./bin/ejercicio14.bin; clear; clear; g++  -o ./bin/ejercicio14.bin ejercicio14.cpp; ./bin/ejercicio14.bin

15: 
	rm ./bin/ejercicio15.bin; clear; clear; g++  -o ./bin/ejercicio15.bin ejercicio15.cpp; ./bin/ejercicio15.bin

16: 
	rm ./bin/ejercicio16.bin; clear; clear; g++  -o ./bin/ejercicio16.bin ejercicio16.cpp; ./bin/ejercicio16.bin

17: 
	rm ./bin/ejercicio17.bin; clear; clear; g++  -o ./bin/ejercicio17.bin ejercicio17.cpp; ./bin/ejercicio17.bin

18: 
	rm ./bin/ejercicio18.bin; clear; clear; g++  -o ./bin/ejercicio18.bin ejercicio18.cpp; ./bin/ejercicio18.bin

19: 
	rm ./bin/ejercicio19.bin; clear; clear; g++  -o ./bin/ejercicio19.bin ejercicio19.cpp; ./bin/ejercicio19.bin

20: 
	rm ./bin/ejercicio20.bin; clear; clear; g++  -o ./bin/ejercicio20.bin ejercicio20.cpp; ./bin/ejercicio20.bin

21: 
	rm ./bin/ejercicio21.bin; clear; clear; g++  -o ./bin/ejercicio21.bin ejercicio21.cpp; ./bin/ejercicio21.bin