1: 
	rm ./bin/ejercicio01; clear; clear; g++  -o ./bin/ejercicio01 ejercicio01.cpp; ./bin/ejercicio01

2: 
	rm ./bin/ejercicio02; clear; clear; g++  -o ./bin/ejercicio02 ejercicio02.cpp; ./bin/ejercicio02

3: 
	rm ./bin/ejercicio03; clear; clear; g++  -o ./bin/ejercicio03 ejercicio03.cpp; ./bin/ejercicio03

4: 
	rm ./bin/ejercicio04; clear; clear; g++  -o ./bin/ejercicio04 ejercicio04.cpp; ./bin/ejercicio04

5: 
	rm ./bin/ejercicio05; clear; clear; g++  -o ./bin/ejercicio05 ejercicio05.cpp; ./bin/ejercicio05

6: 
	rm ./bin/ejercicio06; clear; clear; g++  -o ./bin/ejercicio06 ejercicio06.cpp; ./bin/ejercicio06

7: 
	rm ./bin/ejercicio07; clear; clear; g++  -o ./bin/ejercicio07 ejercicio07.cpp; ./bin/ejercicio07

8: 
	rm ./bin/ejercicio08; clear; clear; g++  -o ./bin/ejercicio08 ejercicio08.cpp; ./bin/ejercicio08

9: 
	rm ./bin/ejercicio09; clear; clear; g++  -o ./bin/ejercicio09 ejercicio09.cpp; ./bin/ejercicio09

10: 
	rm ./bin/ejercicio10; clear; clear; g++  -o ./bin/ejercicio10 ejercicio10.cpp; ./bin/ejercicio10

11: 
	rm ./bin/ejercicio11; clear; clear; g++  -o ./bin/ejercicio11 ejercicio11.cpp; ./bin/ejercicio11

12: 
	rm ./bin/ejercicio12; clear; clear; g++  -o ./bin/ejercicio12 ejercicio12.cpp; ./bin/ejercicio12

13: 
	rm ./bin/ejercicio13; clear; clear; g++  -o ./bin/ejercicio13 ejercicio13.cpp; ./bin/ejercicio13

14: 
	rm ./bin/ejercicio14; clear; clear; g++  -o ./bin/ejercicio14 ejercicio14.cpp; ./bin/ejercicio14

15: 
	rm ./bin/ejercicio15; clear; clear; g++  -o ./bin/ejercicio15 ejercicio15.cpp; ./bin/ejercicio15

16: 
	rm ./bin/ejercicio16; clear; clear; g++  -o ./bin/ejercicio16 ejercicio16.cpp; ./bin/ejercicio16

17: 
	rm ./bin/ejercicio17; clear; clear; g++  -o ./bin/ejercicio17 ejercicio17.cpp; ./bin/ejercicio17

18: 
	rm ./bin/ejercicio18; clear; clear; g++  -o ./bin/ejercicio18 ejercicio18.cpp; ./bin/ejercicio18

19: 
	rm ./bin/ejercicio19; clear; clear; g++  -o ./bin/ejercicio19 ejercicio19.cpp; ./bin/ejercicio19

20: 
	rm ./bin/ejercicio20; clear; clear; g++  -o ./bin/ejercicio20 ejercicio20.cpp; ./bin/ejercicio20

21: 
	rm ./bin/ejercicio21; clear; clear; g++  -o ./bin/ejercicio21 ejercicio21.cpp; ./bin/ejercicio21